[timer]
# the time before a downloaded file is cleaned off the data folder
deleteTimer = 1500000 # 25 minutes

[server]
port = 4500 
zipArguments = "-0rD" 
zipBinaryLocation = "zip" # location of the zip utility binary

[limits]
searchLimit = 15 # the max amount of search results to send to the client

[deemix]
albumNameTemplate = "%artist% - %album%" 
albumTrackNameTemplate = "%tracknumber%. %artist% - %title%" 
createM3U8File = false # create a m3u8 playlist file or not
downloadLocation = 'data/' 
embeddedArtworkPNG = true 
embeddedArtworkSize = 800 
jpegImageQuality = 80 
localArtworkFormat = "jpg" 
localArtworkSize = 1200 
removeDuplicateArtists = true 
saveArtwork = true # put the cover art file inside of the folder
trackFormat = "MP3_128" # ["FLAC", "MP3_320", "MP3_128" or "DEFAULT"]
trackNameTemplate = "%artist% - %title%"
