import type { Metadata } from 'next'
import { SkeletonTheme } from 'react-loading-skeleton'

import 'react-loading-skeleton/dist/skeleton.css'
import '@/styles/layout.css'

export const metadata: Metadata = {
  title: 'SQUID.WTF - Deezer Downloader',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <SkeletonTheme
          baseColor='var(--accent-color)'
          highlightColor='var(--color)'
        >
          {children}
        </SkeletonTheme>
      </body>
    </html>
  )
}
