import type { Metadata } from 'next'

import '@/styles/layout.css'
import Header from './header'

export const metadata: Metadata = {
  title: 'SQUID.WTF - Deezer Downloader',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <main>
          <Header />
          {children}
        </main>
      </body>
    </html>
  )
}
